import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/* ✅ GENERIC VALIDATION */
const validateRecord = (record, requiredFields = []) => {
  const errors = [];

  requiredFields.forEach((field) => {
    if (!record[field]) {
      errors.push(`${field} missing`);
    }
  });

  return errors;
};


/* ✅ GENERIC PDF GENERATOR */
export const generatePDFReport = async ({
  title = "Report",
  data = [],
  fields = [],
  formatField = (val) => val,   // optional formatter
  requiredFields = [],          // validation fields
}) => {

  if (!data || data.length === 0) {
    throw new Error("No data provided");
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ✅ Load Logo
  const img = new Image();
  img.src = "/images/web_Icon.png";

  await new Promise((resolve) => (img.onload = resolve));

  data.forEach((record, index) => {

    /* ✅ VALIDATION */
    const errors = validateRecord(record, requiredFields);

    if (errors.length > 0) {
      console.warn(`Skipping record ${record.id}`, errors);
      return;
    }

    if (index !== 0) doc.addPage();

    let y = 15;

    /* ✅ HEADER */
    doc.addImage(img, "PNG", pageWidth / 2 - 15, y, 30, 15);

    y += 20;

    doc.setFontSize(18);
    doc.setTextColor(0, 102, 153);
    doc.text("HealthGov", pageWidth / 2, y, { align: "center" });

    y += 6;

    doc.setFontSize(11);
    doc.setTextColor(120);
    doc.text(title, pageWidth / 2, y, { align: "center" });

    y += 12;

    doc.line(20, y, pageWidth - 20, y);

    y += 10;

    /* ✅ TITLE (Optional Name) */
    if (record.name) {
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text(record.name, 20, y);
      y += 8;
    }

    /* ✅ BUILD TABLE */
    const tableBody = fields.map((f) => [
      f.label,
      formatField(record[f.key], f.key, record)
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Field", "Value"]],
      body: tableBody,
      theme: "grid",
      styles: {
        fontSize: 10,
        cellPadding: 4,
        lineWidth: 0.5,
      },
      headStyles: {
        fillColor: [34, 197, 94],
        textColor: 255,
      },
    });

    y = doc.lastAutoTable.finalY + 10;

    /* ✅ FOOTER */
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.text(
      "Generated by HealthGov System",
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );

  });

  doc.save(`${title.toLowerCase().replace(/\s/g, "-")}-${Date.now()}.pdf`);
};